#
#
#    Vagrant jenkins deployment environment
#    Copyright (C) 2016 Hiklas Ltd (Katie and Fiona Bianchi)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


   - name: Ensure Jenkins repository is added 
     get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo mode=0644 owner=root group=root

   - name: Ensure Jenkins GPG key is loaded
     get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key dest={{ jenkins_rpm_key_dest }} mode=0644 owner=root group=root

   - name: Ensure Jenkins GPG key is imported 
     command: rpm --import {{ jenkins_rpm_key_dest }}

   - name: Ensure Nginx GPG key is loaded
     get_url: url=http://nginx.org/keys/nginx_signing.key dest={{ nginx_rpm_key_dest }} mode=0644 owner=root group=root

   - name: Ensure Nginx GPG key is imported
     command: rpm --import {{ nginx_rpm_key_dest }}

   - name: Ensure nginx repository is added
     yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present 

   - name: Install packages
     yum: name={{ item }} state=present
     with_items:
       - net-tools
       - maven
       - java-1.8.0-openjdk
       - firewalld
       - git
       - nginx
       - jenkins

   - name: Copy nginx config 
     template: src=./nginx/default.conf dest=/etc/nginx/conf.d/default.conf 

   - name: Enable and start firewalld
     service: name=firewalld enabled=yes state=restarted
  
   - name: Enable firewall services for HTTP(S) permanently
     firewalld: service={{ item }} permanent=true immediate=true state=enabled
     with_items:
       - http
       - https

   - name: Enable firewall for ports
     firewalld: port={{ item }}/tcp permanent=true immediate=true state=enabled
     with_items:
       - 8080

   - name: Enable and start nginx
     service: name=nginx enabled=yes state=restarted

   - name: Enable and start jenkins
     service: name=jenkins enabled=yes state=restarted


