   - name: Ensure Jenkins repository is added 
     get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo mode=0644 owner=root group=root

   - name: Ensure Jenkins GPG key is loaded
     get_url: url=http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key dest={{ jenkins_rpm_key_dest }} mode=0644 owner=root group=root

   - name: Ensure Jenkins GPG key is imported 
     command: rpm --import {{ jenkins_rpm_key_dest }}

   - name: Ensure Nginx GPG key is loaded
     get_url: url=http://nginx.org/keys/nginx_signing.key dest={{ nginx_rpm_key_dest }} mode=0644 owner=root group=root

   - name: Ensure Nginx GPG key is imported
     command: rpm --import {{ nginx_rpm_key_dest }}

   - name: Ensure nginx repository is added
     yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present 

   - name: Install packages
     yum: name={{ item }} state=present
     with_items:
       - git
       - nginx
       - jenkins

   - name: Copy nginx config 
     template: src=./nginx/default.conf dest=/etc/nginx/conf.d/default.conf 

   - name: Enable firewall services for HTTP(S) permanently
     firewalld: service={{ item }} permanent=true immediate=true state=enabled
     with_items:
       - http
       - https

   - name: Enable and start nginx
     service: name=nginx enabled=yes state=restarted

   - name: Enable and start jenkins
     service: name=jenkins enabled=yes state=restarted


